### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by schignel** [alexbruy/getools#1]
Trying to install GETools to QGIS v 3.6.3 via "Install from .zip" option, using the getools-master.zip downloaded from your homepage. 

However, I get the following error, and the tool does not install successfully:

Couldn't load plugin 'getools-master' 

ModuleNotFoundError: No module named 'getools' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\getools-master\__init__.py", line 28, in 
    from getools.getoolsplugin import GeToolsPlugin
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'getools'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c068 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by alexbruy** [comment]
Please, never use files from GitHub unless you perfectly undestand why you need them and how to use them. There is a **repository** with all plugins.

**Comment by schignel** [comment]
Hi Alex,

Can you help me understand how to install your plug-in? I try to search for it through the QGIS plug-in manager but it doesn't appear. So I go to the tool's [homepage](https://plugins.bruy.me/getools.html), but this does not appear to have a download link, rather it links to your [repository](https://plugins.bruy.me/plugins/plugins.xml), which I only see a link to the Homepage or the Source Code. The Source Code takes me to GitHub, where I download the .zip file and get the above error. Am I missing something?

Thanks!
Steve

**Comment by alexbruy** [comment]
@schignel please use my plugins repository to install plugins, not GitHub. You need to configure your QGIS to use additional plugins respositories. If you don't know how to use QGIS Plugin manager, please consult QGIS documentation, for example [User Guide](https://docs.qgis.org/testing/en/docs/user_manual/plugins/plugins.html).

**Comment by schignel** [comment]
Thanks for your help @alexbruy, I followed the instructions under section [10.1.3](https://docs.qgis.org/3.4/en/docs/training_manual/qgis_plugins/fetching_plugins.html) and it's working great.
